### ISSUE TITLE
Занятие 2. Задача 3.

### ISSUE THREAD

**Issue by stsdmchv** [firststage0/TkachevV.L#3]
Проверь решение

**Comment by firststage0** [comment]
> Проверь решение

А что  с ним не так, оно вроде верное.

**Comment by stsdmchv** [comment]
> вроде

так "вроде" или "верное"?
На каких данных проверял?

**Comment by firststage0** [comment]
> > вроде
> 
> так "вроде" или "верное"?
> На каких данных проверял?

Ну, в одном дне 1440 минут(24 часа), электронные часы вместо 24:00 показывают 00:00, и получается если ввести 1444 минуты, то эти часы будут показывать 00:04. Разве не так?

**Comment by firststage0** [comment]
сделано
